### ISSUE TITLE
whenever reboot the host, the word press shows fresh installation page 

### ISSUE THREAD

**Issue by lockelost** [selloween/docker-wordpress#15]
Hi,

I see all the files mounted on my host shows the latest modification-time.
So it looks like the data is persistent. I don't understand why this happens.
Anybody had a similar issue?

```
version: '3.8'

services:

  db:
    container_name: $DB_CONTAINER
    image: mariadb:latest
    restart: "no"
    volumes:
      - ./db_data:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  wp:
    container_name: $WP_CONTAINER
    image: wordpress:latest
    depends_on:
      - db
      - cp
    restart: "no"
    volumes:
      - ./wp_data:/var/www/html:rw
    environment:
      WORDPRESS_DB_HOST: $DB_CONTAINER
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WP_TABLE_PREFIX
      VIRTUAL_HOST: $VIRTUAL_HOST
      VIRTUAL_PORT: $VIRTUAL_PORT
      LETSENCRYPT_HOST: $VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
      #LETSENCRYPT_TEST: 'true'

  cp:
    build: composer
    container_name: ${COMPOSER_CONTAINER}
    volumes:
      - ./wp_data:/app/wp-content:rw
    command: composer install

networks:
  default:
    external:
      name: nginx_proxy

````
